name: DevCard

on:
  schedule:
    - cron: "0 0 * * *"

  workflow_dispatch:

jobs:
  devcard:
    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps:
      - name: devcard
        uses: dailydotdev/action-devcard@2.0.6
        with:
          devcard_id: ${{ secrets.DEVCARD_ID }}
